language: node_js
node_js:
  - 12.13.1
cache: npm

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: script
  script: npm run build
  local_dir: dist
  on:
    branch: master
